name: "Contrast Check"
on:
  pull_request:
    paths:
      - 'css/brands.css'
  push:
    paths:
      - 'css/brands.css'
  workflow_dispatch:

jobs:
  contrast-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Fetch main branch
        run: git fetch origin main:main
      
      - name: Debug information
        run: |
          echo "Current branch: $(git branch --show-current)"
          echo "Modified files in PR:"
          git diff --name-only origin/main

      - name: Run Contrast Check
        run: |
          chmod +x ./scripts/audit-contrast.sh
          ./scripts/audit-contrast.sh
